### PR TITLE
Container build

### PR DESCRIPTION
**Pull request by WildCard65**
Switches travis to build in container mode.

### CODE REVIEW

**Comment by WildCard65** [comment]
I'll have to think on how to get it to link

**Comment by Arkshine** [comment]
Ahah, thanks! Looks like you have some trouble. 

I've no idea how to fix, but it seems it uses clang-3.4 even though you want to use 3.5.
And g++-multilib is not installed too, not sure if needed;

**Comment by WildCard65** [comment]
I need to get travis to whitelist g++-multilib

**Comment by Arkshine** [comment]
Ah, you need to open issue here https://github.com/travis-ci/apt-package-whitelist -_-

**Comment by WildCard65** [comment]
No, it's here: https://github.com/travis-ci/travis-ci/issues and also: https://github.com/travis-ci/travis-ci/issues/3595

**Comment by WildCard65** [comment]
I should also mention this pr is based off of https://github.com/alliedmodders/sourcemod/pull/311

**Comment by WildCard65** [comment]
@Arkshine the travis was a success

**Comment by Arkshine** [comment]
Nice! Thanks.

**Comment by WildCard65** [comment]
Going to run 1 more experiment on package list b4 you can merge.

**Comment by WildCard65** [comment]
@Arkshine ready for merging

**Pull request merged**
